package com.alexandreburghesi.wattsupenergy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApiassistenciaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiassistenciaAllPropertiesEquals(Apiassistencia expected, Apiassistencia actual) {
        assertApiassistenciaAutoGeneratedPropertiesEquals(expected, actual);
        assertApiassistenciaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiassistenciaAllUpdatablePropertiesEquals(Apiassistencia expected, Apiassistencia actual) {
        assertApiassistenciaUpdatableFieldsEquals(expected, actual);
        assertApiassistenciaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiassistenciaAutoGeneratedPropertiesEquals(Apiassistencia expected, Apiassistencia actual) {
        assertThat(actual)
            .as("Verify Apiassistencia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiassistenciaUpdatableFieldsEquals(Apiassistencia expected, Apiassistencia actual) {
        assertThat(actual)
            .as("Verify Apiassistencia relevant properties")
            .satisfies(a -> assertThat(a.getFiltro()).as("check filtro").isEqualTo(expected.getFiltro()))
            .satisfies(a -> assertThat(a.getDadosassistencia()).as("check dadosassistencia").isEqualTo(expected.getDadosassistencia()))
            .satisfies(a -> assertThat(a.getChave()).as("check chave").isEqualTo(expected.getChave()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiassistenciaUpdatableRelationshipsEquals(Apiassistencia expected, Apiassistencia actual) {
        // empty method
    }
}
