package com.alexandreburghesi.wattsupenergy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApiperiodoassistenciaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiperiodoassistenciaAllPropertiesEquals(Apiperiodoassistencia expected, Apiperiodoassistencia actual) {
        assertApiperiodoassistenciaAutoGeneratedPropertiesEquals(expected, actual);
        assertApiperiodoassistenciaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiperiodoassistenciaAllUpdatablePropertiesEquals(
        Apiperiodoassistencia expected,
        Apiperiodoassistencia actual
    ) {
        assertApiperiodoassistenciaUpdatableFieldsEquals(expected, actual);
        assertApiperiodoassistenciaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiperiodoassistenciaAutoGeneratedPropertiesEquals(
        Apiperiodoassistencia expected,
        Apiperiodoassistencia actual
    ) {
        assertThat(actual)
            .as("Verify Apiperiodoassistencia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiperiodoassistenciaUpdatableFieldsEquals(Apiperiodoassistencia expected, Apiperiodoassistencia actual) {
        assertThat(actual)
            .as("Verify Apiperiodoassistencia relevant properties")
            .satisfies(a -> assertThat(a.getDadosperiodo()).as("check dadosperiodo").isEqualTo(expected.getDadosperiodo()))
            .satisfies(a -> assertThat(a.getChave()).as("check chave").isEqualTo(expected.getChave()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiperiodoassistenciaUpdatableRelationshipsEquals(
        Apiperiodoassistencia expected,
        Apiperiodoassistencia actual
    ) {
        // empty method
    }
}
