package com.alexandreburghesi.wattsupenergy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssistenciasAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistenciasAllPropertiesEquals(Assistencias expected, Assistencias actual) {
        assertAssistenciasAutoGeneratedPropertiesEquals(expected, actual);
        assertAssistenciasAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistenciasAllUpdatablePropertiesEquals(Assistencias expected, Assistencias actual) {
        assertAssistenciasUpdatableFieldsEquals(expected, actual);
        assertAssistenciasUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistenciasAutoGeneratedPropertiesEquals(Assistencias expected, Assistencias actual) {
        assertThat(actual)
            .as("Verify Assistencias auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistenciasUpdatableFieldsEquals(Assistencias expected, Assistencias actual) {
        assertThat(actual)
            .as("Verify Assistencias relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistenciasUpdatableRelationshipsEquals(Assistencias expected, Assistencias actual) {
        assertThat(actual)
            .as("Verify Assistencias relationships")
            .satisfies(a -> assertThat(a.getApiassistencia()).as("check apiassistencia").isEqualTo(expected.getApiassistencia()));
    }
}
